# Generated by Django 3.1 on 2020-08-20 08:20

from django.db import migrations, models
import django_sharding_library.fields
import django_sharding_library.id_generation_strategies


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', django_sharding_library.fields.TableShardedIDField(primary_key=True, serialize=False, source_table_name='api.PostIDs', strategy=django_sharding_library.id_generation_strategies.TableStrategy(backing_model_name='api.PostIDs'))),
                ('title', models.CharField(max_length=128, unique=True)),
                ('user_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'posts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PostIDs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stub', models.NullBooleanField(default=True, unique=True)),
            ],
            options={
                'db_table': 'post_ids',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
    ]
